extraction:
  cpp:
    after_prepare: 
      - python report.py 41
  cobol:
    after_prepare: 
      - python report.py 41
  csharp:
    after_prepare: 
      - python report.py 41
  java:
    after_prepare: 
      - python report.py 41
  javascript:
    after_prepare: 
      - python report.py 41
  python:
    after_prepare: 
      - python report.py 41
